feat(pipelines transform): forbid nesting pipelines transform
vectordotdev/vector pull request #10098
Opened 2021-11-18 08:21 UTC by jdrouet

The pipelines transform should not be nested in another pipelines transform.
This PR adds a new `nestable` method to the `TransformConfig` trait to check if a transform can be embedded in some parent transforms.
For now, it's only used by the pipelines transform and the result defaults to `true` for all the other transforms.

Signed-off-by: Jérémie Drouet <jeremie.drouet@datadoghq.com>

2021-11-18 16:26 UTC, binarylogic approved these changes
Approving the restriction in general

2021-11-19 15:29 UTC, tobz approved these changes
This makes sense to me. 👍🏻

2021-11-19 19:42 UTC, vladimir-dd commented
@binarylogic could we clarify what would be the way to support nested pipelines please?

2021-11-19 19:46 UTC, jszwedko requested changes
Just noting per the conversation offline that we need to follow up to see how we want to represent nested Log Pipelines pipelines before merging this.

2021-11-19 22:48 UTC, lukesteensen reviewed
I also agree with this in theory but am not familiar enough with the nested pipelines case to really weigh in.

2021-11-23 16:10 UTC, vladimir-dd approved these changes

2021-11-23 16:59 UTC, jdrouet commented
@jszwedko, @vladimir-dd and @binarylogic concluded that it'd be good to go. If that's ok with you, you can approve the changes and it will be merged 😉

2021-11-23 18:26 UTC, jszwedko commented
@vladimir-dd do the current configs we are soak testing require nested pipelines? I'm just curious if we should solve #9991 first and allow nested pipelines to be directly configured before prohibiting nested `pipelines` transforms.

2021-11-24 18:14 UTC, vladimir-dd commented
@jszwedko, @jdrouet the public config used for soak tests contains no nested pipelines so we can merge this PR and completely disable nested pipelines(any level deep) as we agreed.

2021-11-24 18:42 UTC, jszwedko approved these changes

2021-11-24 18:42 UTC, merged