docs: Add cue schema for structured release changelogs
vectordotdev/vector pull request #10140
Opened 2021-11-22 23:08 UTC by jszwedko

I migrated the 0.18.0.cue release file as an example (though I didn't go
back and try to dig up all of the relevant pull requests to add the
numbers; we can do this moving forward).

Assuming we are on-board with this change, I think next steps would be:

* Update the website to render the changelog if it exists
* Remove the changelog from 0.18.0 description since it'll now be
  rendered from the structured data
* Backport structured changelog data for previous releases (optional?
  Maybe we just do the last few?)
* Remove commit list from releases and instead link to Github diff
* Update `scripts/release-prepare` to output the log file for reference
  to create the structured changelog list, but not use it to generate
  the commit list automatically

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

2021-11-23 20:58 UTC, lucperkins requested changes

2021-11-23 20:58 UTC, lucperkins commented on website/cue/reference/releases/0.18.0.cue
> +			description: """
All of the descriptions need to be brought in line with [these conventions](https://github.com/vectordotdev/vector/tree/master/website#watch-your-indentation) lest the Markdown parser interpret them as code blocks.

2021-12-20 18:41 UTC, jszwedko commented
@binarylogic do you mind giving this a look? I think it is ready now.

2021-12-20 18:51 UTC, binarylogic approved these changes

2021-12-20 18:53 UTC, merged