enhancement(aws sink): Make TLS options configurable for AWS sinks
vectordotdev/vector pull request #10314
Opened 2021-12-06 23:49 UTC by ChinYing-Li

The PR aims to address #4516 ; I will update the docs and `.cue` files once everything looks good to people.
Any suggestion is appreciated!
Signed-off-by: ChinYing-Li <chinying.li@mail.utoronto.ca>

2021-12-07 17:05 UTC, fuchsnj commented
The code changes look fine. Please update the documentation for the sinks this impacted to add the new `TLS` options. You can find an example here: https://github.com/vectordotdev/vector/blob/master/website/cue/reference/components/sinks/splunk_hec_logs.cue#L44-L49

Once you push the changes, the `netlify` bot will give you a preview of the doc changes.

2021-12-07 17:15 UTC, bruceg requested changes
I agree with @fuchsnj, the code looks fine but this needs docs. I noted a couple of issues that the format check is complaining about, so you'll need to run `cargo fmt` to fix them.

2021-12-07 17:15 UTC, bruceg commented on src/sinks/aws_cloudwatch_logs/mod.rs
> +        let client = self.create_client( cx.proxy())?;
This added space seems accidental.

2021-12-07 17:15 UTC, bruceg commented on src/sinks/aws_cloudwatch_logs/mod.rs
> +        let client = config.create_client( &ProxyConfig::from_env()).unwrap();
Ditto

2022-02-15 15:58 UTC, fuchsnj approved these changes

2022-02-15 17:40 UTC, bruceg approved these changes

2022-02-15 22:02 UTC, merged

2022-02-15 22:02 UTC, jszwedko commented
Thank you for this contribution @ChinYing-Li !