chore: Shrink the visible soak test boilerplate explanation
vectordotdev/vector pull request #10331
Opened 2021-12-07 21:43 UTC by bruceg

2021-12-07 22:43 UTC, bruceg commented
Hmm, odd, there is a paragraph break in the "Explanation" but no paragraph break in the rendered output.

2021-12-07 23:04 UTC, blt requested changes

2021-12-07 23:04 UTC, blt commented on soaks/bin/analyze_experiment
> +print()
So this isn't quite correct, I don't think. The paragraph here won't make sense if there are no changes, considering that the table being referenced doesn't exist. A rewording to describe the sections that follow and their purpose would work though, for this non-conditional approach.

2021-12-07 23:05 UTC, jszwedko commented
I'm betting Github doesn't apply the same markdown rendering in HTML blocks like `<details>`. You can see in https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections that they additionally use `<p>` tags for paragraphs.

2021-12-08 20:15 UTC, blt approved these changes

2021-12-08 22:39 UTC, merged