docs(splunk service): added highlight article for Splunk HEC improvements
vectordotdev/vector pull request #10473
Opened 2021-12-15 19:36 UTC by barieom

2021-12-15 20:09 UTC, binarylogic commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +With the new support for Splunk HEC indexer acknowledgement, Vector now provides a
```suggestion
## Indexer Acknowledgements

With the new support for Splunk HEC indexer acknowledgement, Vector now provides a
```

2021-12-15 20:10 UTC, binarylogic commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +Vector now also supports new token passthrough routing. You can now use these tokens,
```suggestion
## Passthrough Token Routing

Vector now also supports new token passthrough routing. You can now use these tokens,
```

2021-12-15 20:14 UTC, 001wwang reviewed
Awesome! Left some comments mostly on rewording and whether we'd want to highlight the `splunk_hec` source changes as well. Happy to chat about anything.

2021-12-15 20:14 UTC, 001wwang commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +can now use that token in the `splunk_hec` sink to forward logs. With this update,
This seems slightly repetitive with the previous sentence. Perhaps combine them into something like: 
> "When `store_hec_token` is enabled in a `splunk_hec` source, tokens included in requests to the source will be stored and used by downstream `splunk_hec` sinks. Any passed through token takes precedence over the `default_token` configuration set in the sink." 

Side note: the token passthrough works for both `splunk_hec` metrics and logs sinks so "to foward logs" may be a bit confusing.

2021-12-15 20:14 UTC, 001wwang commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +you can now partition event batches in the `splunk_hec` sinks by token.
I think you can leave this partitioning bit out as it's more of a minor implementation detail.

2021-12-15 20:29 UTC, jszwedko reviewed
Looks good!

I agree with Will that we should highlight the improvements to the `splunk_hec` source as well. These would be:

* The `splunk_hec` source now implements the Splunk HEC ack protocol to notify senders when the data has been successfully processed
* The `splunk_hec` source is now integrated into Vector's end-to-end acknowledgments so that it only acks events that have been processed by sinks (or disk buffers)

I might also add some configuration snippets to show how to enable and use these features.

2021-12-15 20:29 UTC, jszwedko commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +for Splunk HEC; Vector now supports Splunk HEC indexer acknowledgements and
I might add some links to the Splunk HEC docs for people who are familiar with Splunk, but not the HEC format.

2021-12-15 20:29 UTC, jszwedko commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +if it receives a 200. Vector will now check [Splunk HEC indexer acknowledgements][Splunk indexer]
```suggestion
if it responds to the incoming request successfully. Vector will now check [Splunk HEC indexer acknowledgements][Splunk indexer]
```

2021-12-15 20:29 UTC, jszwedko commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +how it works, check out the short explanation in the Vector [sinks reference page][indexer how it works].
```suggestion
how it works, check out the short explanation in the Vector [`splunk_hec` sink reference page][indexer how it works].
```

2021-12-20 22:51 UTC, jszwedko commented
@barieom I think this one still needs revised based on the feedback. I'm happy to take another look after that!

2021-12-23 16:32 UTC, jszwedko commented
@001wwang could you give this another look over?

2021-12-23 17:30 UTC, 001wwang requested changes
Nice! Suggested some changes to the wording and explanations that I think are worth making.

2021-12-23 17:30 UTC, 001wwang commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +endpoint][indexer].
```suggestion
written when it responds to an incoming request successfully. To confirm that data has been persisted, the [indexer acknowledgements][indexer] feature must be enabled. The status of sent events can then be queried via a separate endpoint.
```

2021-12-23 17:30 UTC, 001wwang commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +acknowledgement requests from clients by configuring:
```suggestion
Now, you can configure the `splunk_hec` source to use the indexer acknowledgements protocol by configuring:
```

2021-12-23 17:30 UTC, 001wwang commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +for querying for ack status by clients, this also wires into Vector's
```suggestion
When enabled, responses to incoming requests will include an ID that can be used to query for acknowledgement status at the newly exposed `/services/collector/ack` endpoint ([learn more here][indexer how it works]). The acknowledgement status is wired into Vector's
```

2021-12-23 17:30 UTC, 001wwang commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +Splunk reciever acknowledges the events via the [index
```suggestion
Splunk receiver acknowledges the events via the [index
```

2021-12-23 17:30 UTC, 001wwang commented on website/content/en/highlights/2021-12-15-splunk-hec-improvements.md
> +`splunk_hec` sinks by token.
```suggestion
set in the sink.
```

2021-12-23 20:10 UTC, jszwedko commented
@001wwang thanks! I applied your suggestions.

2021-12-23 21:27 UTC, 001wwang approved these changes

2021-12-23 21:44 UTC, merged