enhancement(datadog_agent source): comply with component spec
vectordotdev/vector pull request #10932
Opened 2022-01-20 15:11 UTC by jdrouet

Add `EventsSent` and `StreamError` metrics

Closes #10059

Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>

2022-01-21 18:26 UTC, bruceg requested changes

2022-01-21 18:26 UTC, bruceg commented on src/internal_events/datadog_agent.rs
> +}
As indicated in my previous review, I think this should be a generic error for all sources.

2022-01-21 18:26 UTC, bruceg commented on src/internal_events/datadog_agent.rs
> +            error_type = "stream",
I recommend something like `stream_closed` for these, although that may be too confusing, as it sounds like maybe _upstream_ was closed, which is not what this is describing.

2022-01-21 18:26 UTC, bruceg commented on src/sources/datadog/agent/mod.rs
> +                emit!(&EventsSent { count, byte_size });
Noting as per the other review, this is not needed for sources.

2022-01-26 08:11 UTC, jdrouet commented
@bruceg all your suggestions have been addressed, could you take another look?

2022-01-27 00:30 UTC, bruceg approved these changes

2022-01-27 08:42 UTC, merged

2022-02-03 00:26 UTC, jszwedko reviewed
Again, here, I believe that the reported `component_received_event_bytes_total` is inaccurate. It appears to be reporting the raw bytes rather than the in-memory representation via `BytesSizeOf::size_of`.

I realize that you didn't change that, but part of this survey should include making sure the existing metrics are accurate 😄

2022-02-03 10:01 UTC, jdrouet commented
@jszwedko that's quite weird, it's using `BytesSizeOf` [here](https://github.com/vectordotdev/vector/blob/master/src/sources/datadog/agent/mod.rs#L428), [here](https://github.com/vectordotdev/vector/blob/master/src/sources/datadog/agent/mod.rs#L463) and [here](https://github.com/vectordotdev/vector/blob/master/src/sources/datadog/agent/mod.rs#L534). 🤔 Do I miss something?

2022-02-03 15:23 UTC, jszwedko commented
> @jszwedko that's quite weird, it's using `BytesSizeOf` [here](https://github.com/vectordotdev/vector/blob/master/src/sources/datadog/agent/mod.rs#L428), [here](https://github.com/vectordotdev/vector/blob/master/src/sources/datadog/agent/mod.rs#L463) and [here](https://github.com/vectordotdev/vector/blob/master/src/sources/datadog/agent/mod.rs#L534). 🤔 Do I miss something?

Ah, hmm, I thought I left this comment on the `socket` source. You are right, this one seems to be ok. Apologies for the confusion!