chore(releasing): Prepare v0.19.1
vectordotdev/vector pull request #11005
Opened 2022-01-24 19:58 UTC by jszwedko

2022-01-24 21:03 UTC, spencergilbert requested changes
Call me crazy but we're missing https://github.com/vectordotdev/vector/pull/10948/files#diff-e76eab15ec40a1f8b5d8857a3c2a7ff87baf5641ae5e40f25e2e87e7c79cfa46

2022-01-24 21:08 UTC, jszwedko commented
> Call me crazy but we're missing https://github.com/vectordotdev/vector/pull/10948/files#diff-e76eab15ec40a1f8b5d8857a3c2a7ff87baf5641ae5e40f25e2e87e7c79cfa46

Thanks for the close eye 😄 That change actually got dropped because the bug it is fixing was introduced in master after 0.19. In 0.19, forward is still being used:

https://github.com/vectordotdev/vector/blob/ea870e1b5cbfaa8782fe96dc5af06722e58def5a/src/topology/builder.rs#L172

That confused me initially too when cherry picking.

2022-01-24 21:10 UTC, spencergilbert commented
Doh, gotcha 😆

2022-01-25 14:55 UTC, spencergilbert approved these changes

2022-01-25 16:28 UTC, merged