enhancement(nats source): comply with component spec
vectordotdev/vector pull request #11120
Opened 2022-02-01 08:25 UTC by jdrouet

Adds `BytesReceived`, `StreamClosedError` and update `NatsEventsReceived`.
Also converts `out.send` to `out.send_all`.

closes #10072

Signed-off-by: Jérémie Drouet <jeremie.drouet@datadoghq.com>

2022-02-01 20:06 UTC, 001wwang approved these changes
Nice, just one very minor suggestion.

2022-02-02 23:39 UTC, jszwedko requested changes
One question about the accounting of `component_received_event_bytes_total` here.

2022-02-02 23:39 UTC, jszwedko commented on src/sources/nats.rs
> +                    emit!(&NatsEventsReceived { byte_size, count });
I don't think the `byte_size` here is right. The `byte_size` returned by the decoder is actually the number of bytes from the frame, so basically the same as received bytes above that is published as `component_received_bytes_total`:

https://github.com/vectordotdev/vector/blob/86bfec8d70cb30158964a0208d37b30723be3e8f/src/codecs/decoding.rs#L191-L216

Instead, `component_received_event_bytes_total` should reflect the total deserialized event bytes in-memory. That is, you should sum up `ByteSizeOf::size_of` of the events here.

2022-02-03 16:01 UTC, jszwedko approved these changes
Thanks for the updates!

2022-02-03 16:22 UTC, merged