chore(ci): Use the mold wrapper script instead of linker flags
vectordotdev/vector pull request #13125
Opened 2022-06-13 18:37 UTC by bruceg

2022-06-13 18:48 UTC, spencergilbert approved these changes

2022-06-13 18:52 UTC, tobz requested changes
Looks good to me overall, but one I'mpretty-sure-you-need-to-fix-this comment and one actual non-blocking nit.

2022-06-13 18:52 UTC, tobz commented on scripts/environment/bootstrap-ubuntu-20.04.sh
> +exec mold -run "$@"
I think you'll need to `chmod +x "$RUST_WRAPPER"` so it can actually be executed?

2022-06-13 18:52 UTC, tobz commented on scripts/environment/bootstrap-ubuntu-20.04.sh
> +RUST_WRAPPER="${CARGO_BIN_DIR}/wrap-rustc"
Super small nit: probably want to call this `RUSTC_WRAPPER`.

2022-06-13 20:30 UTC, tobz approved these changes
As promised, the remaining nit is non-blocking so this LGTM.

(also modulo all the other broken stuff in CI we're all simultaneously trying to fix)

2022-06-13 21:15 UTC, jszwedko commented
Still seems to be failing:

```
  mold: fatal: mold-wrapper.so is missing
```

2022-06-13 21:17 UTC, tobz commented
> Still seems to be failing:

I'm fixing this.

2022-06-14 00:04 UTC, tobz commented on scripts/cross/bootstrap-ubuntu.sh
> -
Simply made to trigger the "Cross" workflow steps.. but it's just whitespace changing so who cares.

2022-06-14 00:07 UTC, tobz commented on .github/workflows/k8s_e2e.yml
> +  DISABLE_MOLD: true
We disable installing/configuring `mold` on the test runner host for the Kubernetes E2E tests _because_ `cross` carries over Cargo configuration to the build container, which means the `rustc` wrapper, and `mold`, would need to exist in the build container... and also support the target triple.

It's just easier to skip it in that case. Other usages of `cross` don't actually install/configure `mold` on the test runner host (i.e. they don't run `bootstrap-ubuntu-20.04.sh`) so we don't need to tweak those workflows to disable it.

2022-06-14 00:11 UTC, tobz commented on .github/workflows/k8s_e2e.yml
> +  DISABLE_MOLD: true
That said, we might not even need to run `bootstrap-ubuntu-20.04.sh` on the test runner host... maybe that's just a historical hold-over. I'm not sure, and I'm leaving it as a future potential optimization.

2022-06-14 00:11 UTC, merged

2022-06-14 02:18 UTC, jszwedko reviewed
👍 thanks for this fix!