feat(source) opentelemetry-log
vectordotdev/vector pull request #13135
Opened 2022-06-14 05:28 UTC by caibirdme

Too many commits in another PR, so I created the new clear one.

```yaml
sources:
  otel:
    type: opentelemetry
    address: 0.0.0.0:6788
```

* lib/opentelemetry: otel-proto & impl From Trait to convert proto type into vector::Event
* src/soruces/opentelemetry: source plugin to setup a grpc server to receive log request

2022-06-21 13:17 UTC, StephenWakely requested changes
Nice work. Many thanks for submitting this! It's exciting to see us get moving into OpenTelemetry. 

I've managed to test this using the open telemetry collector and it is working nicely. I've thrown down a few initial comments, nothing major. 

If you can tidy up the PR I'll take another look shortly.

2022-06-21 13:17 UTC, StephenWakely commented on lib/opentelemetry/src/convert.rs
> +        le.insert(SEVERITY_NUMBER_KEY, rl.log_record.severity_number as i64);
Severity and severity number are also optional. Can we suppress inserting if they aren't specified (0 or empty string).

2022-06-21 13:17 UTC, StephenWakely commented on lib/opentelemetry/src/convert.rs
> +            le.insert(RESOURCE_KEY, kv_list_into_value(resource.attributes));
Can we suppress inserting this if it is empty.

2022-06-21 13:17 UTC, StephenWakely commented on lib/opentelemetry/src/convert.rs
> +        );
Can we supress this if the time is == 0.

2022-06-24 02:11 UTC, caibirdme commented on lib/opentelemetry/src/lib.rs
> +}
What does the tidy up mean exactly? I did 'git rebase master' and then this pr contains lots of other people's commit... It's out of my expectation. So, do I need to create a new clean branch to resolve these problems or just continue to commit on this branch

2022-06-29 01:51 UTC, closed without merging