enhancement(prometheus_scrape source): update bucket size to u64
vectordotdev/vector pull request #13318
Opened 2022-06-24 11:12 UTC by StephenWakely

Closes #12043

2022-06-24 17:51 UTC, jszwedko reviewed
Nice! I was expecting this to take much longer. I still need to review in detail, but just a note that we should make sure to put together a note for the upgrade guide since users could run into issues with this change. We should note:

* That disk buffers should be backed up if you want to be able to rollback since new disk buffer entries may not be readable by older Vector versions
* Users sending events between Vector instances should upgrade the consumers first, then the producers

2022-06-24 22:30 UTC, bruceg approved these changes

2022-06-27 23:12 UTC, tobz requested changes

2022-06-27 23:31 UTC, tobz commented
> > * `DDSketch` stores u32, this means in `insert_interpolate_buckets` we now check that the count fits into `u32` and error if it doesn't. This means `DatadogMetricsNormalizer` will drop the metric if it is > `u32::MAX`. Is this an ok thing to do?
> 
> I think Toby had ideas here around splitting the bucket?

At a high-level, we force all aggregated histograms into incremental versions, so the only way to violate bucket counts being less than or equal to `u32::MAX` would imply a bucket count growing by `u32::MAX` or more from one update to the next... not impossible, but practically won't ever happen.

As far as splitting the bins in the sketch: I double checked, and it's already implemented internally and will happen automatically... but the problem is that bin counts are `u16`. This means we would need 2^16 bins to represent a single histogram bucket having even a count of `u32::MAX` without this PR, or 2^48 bins to represent a count of `u64::MAX`. This is already not going to be possible with the sketch defaults we use, which limit us to a maximum of 4096 bins per sketch. Practically, this still limits us to a single bucket in an aggregated histogram changing its count by ~268 million or less to avoid an overflow..

It'd be nice if we had a more compile-time/type-level way to do all of this, but I think the best we can do is maybe log an error when we encounter such a weird incremental aggregated histogram in the DD metrics normalizer. 🤷🏻

2022-06-29 15:59 UTC, StephenWakely commented
> Do you know how InfluxDB responds when you send a u64?

Ok have tested this. It seems that (at least the Docker builds) are capable of receiving u64 fine. If I do send a count that is definitely out of range, Influx will return a 400 error.

2022-06-29 16:06 UTC, jszwedko commented
> > Do you know how InfluxDB responds when you send a u64?
> 
> Ok have tested this. It seems that (at least the Docker builds) are capable of receiving u64 fine. If I do send a count that is definitely out of range, Influx will return a 400 error.

Cool, it seems sensible to me to just pass through then.

2022-07-01 16:14 UTC, tobz approved these changes
Yeah, this looks reasonable enough to me. 👍🏻 

Left one small non-blocking nit.

2022-07-01 16:14 UTC, tobz commented on lib/prometheus-parser/src/line.rs
> +
I think you can reduce this section down to a smaller comment that explains that converting from an integer to a floating-point number will start to lose precision once the number is bigger than 2^N, where N is the number of bits in the mantissa (53 bits for an `f64`).

In addition, or alternatively, you could add an assertion that we handle 2^N-1 and 2^N without loss, but that 2^N+1 rounds down to 2^N, to show we're providing a maximally correct conversion where possible.

2022-07-02 12:23 UTC, merged