enhancement(enterprise): drop application_key
vectordotdev/vector pull request #13655
Opened 2022-07-21 11:18 UTC by vladimir-dd

Deprecates `application_key` to setup Observability Pipelines

2022-07-21 14:37 UTC, jszwedko reviewed
Changes generally look OK to me, but just noting that this change isn't backwards compatible with existing installs. I'll let people more familiar chime in with whether that is a requirement.

cc/ @leebenson @sghall @binarylogic

2022-07-28 01:18 UTC, leebenson requested changes
I'm fine with making `application_key` a hard error. It will prompt users that they no longer have to share this class of sensitive key. We also have few - if any - real users, so this shouldn't be a problem.

Just a few CI errors to clear up.

2022-07-28 01:19 UTC, leebenson commented
(And of course, we should ensure all the related work in McNulty is merged first, so this won't break OP!)

2022-08-09 15:37 UTC, leebenson approved these changes

2022-08-10 14:46 UTC, jszwedko commented
Force merging since this breaks the `enterprise_http_to_http` baseline soaks due to changing the soak configuration to not set the `application_key` anymore.

2022-08-10 14:47 UTC, merged