enhancement(geoip transform): Add support for Connection-Type databases
vectordotdev/vector pull request #13707
Opened 2022-07-25 21:15 UTC by w4

Closes #13706

2022-08-01 18:26 UTC, tobz commented on src/transforms/geoip.rs
> +            }
Hmmm, I think this is actually a breaking change, as all of the fields for the given MaxMind database (i.e. the city-specific fields if using the City database, etc) would still be added to the target field, albeit empty, if the IP wasn't parseable or if the source field was missing.

Now the target field will just be `null`.

@jszwedko What do you think? I don't have a strong opinion on `null` overall vs having all the target fields being present but empty.

2022-08-05 18:00 UTC, jszwedko commented
Hey @w4 ! Apologies for not getting to this sooner. This `geoip` transform is actually deprecated now that we've we added support for enriching geoip data via enrichment tables (see: https://github.com/vectordotdev/vector/pull/13338). Would you mind moving these changes over there?

2022-08-06 13:15 UTC, w4 commented
Ah interesting, will do thanks

2022-08-07 10:41 UTC, w4 commented
This is updated now, thanks @jszwedko

2022-08-12 18:13 UTC, jszwedko approved these changes
This looks good, thanks for porting over the logic @w4 !

2022-08-12 18:17 UTC, jszwedko requested changes
Actually, I realized we need to update the docs here too: https://github.com/vectordotdev/vector/blob/e1268b1ad376669dc8069d0bf59d34dedc415b2e/website/cue/reference/remap/functions.cue#L60

I'll push an update.

2022-08-12 18:24 UTC, jszwedko approved these changes

2022-08-12 18:28 UTC, jszwedko commented
@w4 I wasn't able to push to this PR branch for some reason. Would you mind applying the following diff:

```diff
0f3b36b3a - Document support for Connection-Type databases (5 minutes ago) <Jesse Szwedko>
diff --git a/website/cue/reference/remap/functions.cue b/website/cue/reference/remap/functions.cue
index d491c9873..f8fc7df8b 100644
--- a/website/cue/reference/remap/functions.cue
+++ b/website/cue/reference/remap/functions.cue
@@ -82,26 +82,27 @@ remap: {
 		and without a value, `null` will be used. This table can return following fields:
 
 		* ISP databases:
-
 			* `autonomous_system_number`
 			* `autonomous_system_organization`
 			* `isp`
 			* `organization`
 
 		* City databases:
-
 			* `city_name`
 			* `continent_code`
 			* `country_code`
 			* `country_name`
 			* `region_code`
 			* `region_name`
-			* `metro_code`		
+			* `metro_code`
 			* `latitude`
-			* `longitude`		
+			* `longitude`
 			* `postal_code`
 			* `timezone`
 
+		* Connection-Type databases:
+			* `connection_type`
+
 		To use this function, you need to update your Vector configuration to
 		include an
 		[`enrichment_tables`](\(urls.vector_configuration_global)/#enrichment_tables)
```

2022-08-12 19:49 UTC, w4 commented
Not a problem, that's all done - thanks @jszwedko

2022-08-12 20:06 UTC, jszwedko commented
Great, thanks! I marked this to merge once CI passes.

2022-08-15 13:26 UTC, merged

2022-08-15 13:26 UTC, jszwedko commented
Merging since CI failure was from master.