feat(new sink): new `azure_event_hubs` sink.
vectordotdev/vector pull request #13732
Opened 2022-07-27 15:26 UTC by StephenWakely

Closes #4261 

This adds a new source that accepts data from [Azure event hubs](https://docs.microsoft.com/en-gb/azure/event-hubs/event-hubs-about).

It is a simple wrapper over the Kafka source since Event Hubs provides a [Kafka compatible API](https://docs.microsoft.com/en-gb/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview).

It should be noted that the Kafka connection doesn't work with the Basic SKU. Users will need to have a Standard, Premium and Dedicated SKU in order to use this source.

Currently this exposes a minimum set of options that are passed to the Kafka source. I am open to adding more - for example access to the `librdkafka` options if it is deemed that this will be useful.

2022-07-27 16:36 UTC, spencergilbert requested changes
Mostly issues with the docs

2022-07-27 16:36 UTC, spencergilbert commented on src/sources/azure_event_hubs/config.rs
> +/// for details on how `azure_event_hubs` can use `kafka`.
```suggestion
/// See the documentation [here][event_hubs_docs] for details on how `azure_event_hubs` can use `kafka`.
///
///[event_hubs_docs]: https://docs.microsoft.com/en-gb/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview
```

I'd use this format instead - [ref](https://github.com/vectordotdev/vector/blob/master/src/sinks/kafka/config.rs#L67-L71)

2022-07-27 16:36 UTC, spencergilbert commented on src/sources/azure_event_hubs/config.rs
> +/// This component is a simple wrapper over the `kafka` source.
This probably doesn't need to be included as we wouldn't necessarily want it rendered in the docs?

2022-07-27 16:36 UTC, spencergilbert commented on src/sources/azure_event_hubs/config.rs
> +    /// See [here](https://docs.microsoft.com/en-gb/azure/event-hubs/event-hubs-get-connection-string) for details.
```suggestion
    /// See [here][connection_string] for details.
    ///
    /// [connection_string]: https://docs.microsoft.com/en-gb/azure/event-hubs/event-hubs-get-connection-string
```

2022-07-27 16:36 UTC, spencergilbert commented on website/cue/reference/components/sources/azure_event_hubs.cue
> +		deployment_roles: ["daemon", "sidecar"]
Not aggregator?

2022-07-27 16:36 UTC, spencergilbert commented on website/cue/reference/components/sources/azure_event_hubs.cue
> +		acknowledgements: false
```suggestion
		acknowledgements: true
```

2022-07-27 16:36 UTC, spencergilbert commented on website/cue/reference/components/sources/azure_event_hubs.cue
> +                for details on how `azure_event_hubs` can use `kafka`.
I'd rather have this say something like "this component leverages event hubs' compatibility with kafka and requires <whatever account level>..."

2022-07-27 16:36 UTC, spencergilbert commented on Cargo.toml
> +sources-azure_event_hubs = []
Don't need to grab the kafka features here?

2022-07-27 18:29 UTC, jszwedko reviewed
Sweet. This generally looks good to me. Agreed with Spencer's comments on the docs. For rdkafka options, I suggest we wait until someone asks for them.

One thought I did have is that we'll have to refactor this configuration quite a bit if we do end up wanting to support other ways of pulling data from Azure Event Hubs (like their AMQP API).

2022-07-27 18:29 UTC, jszwedko commented on website/cue/reference/components/sources/azure_event_hubs.cue
> +	telemetry: metrics: {
Do we need to add the event processing metrics, like `received_event_bytes_total` here too?

2022-07-27 18:47 UTC, spencergilbert commented
> One thought I did have is that we'll have to refactor this configuration quite a bit if we do end up wanting to support other ways of pulling data from Azure Event Hubs (like their AMQP API).

🤔 what's the likelihood of this, we should get ahead of it if it seems at all likely (ex `opentelemetry` logs, metrics, traces.

2022-07-27 18:55 UTC, jszwedko commented
> > One thought I did have is that we'll have to refactor this configuration quite a bit if we do end up wanting to support other ways of pulling data from Azure Event Hubs (like their AMQP API).
> 
> 🤔 what's the likelihood of this, we should get ahead of it if it seems at all likely (ex `opentelemetry` logs, metrics, traces.

I'm not really sure when someone would need / want to use a specific interface. My gut says it is a low risk, I think we may just need to wait for users to ask for it to understand the use-cases better.

2022-07-27 22:44 UTC, neuronull commented on src/sources/azure_event_hubs/mod.rs
> +}
file is missing a newline

2022-07-27 22:45 UTC, neuronull approved these changes

2022-08-01 11:25 UTC, jeromekleinen-kbc commented
I hope you guys don't mind if I chime in here. I have been using the kafka source to read AEH for quite some time now. What is the advantage of this dedicated source compared to just providing a specific guide? Or in other words: should I switch my existing configs when this lands?

I quickly skimmed the code and I think no specific librdkafka options are set. I have been using the ones specified by Microsoft here: https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/CONFIGURATION.md#librdkafka-configuration-properties

I honestly don't know whether they make any real difference though.

2022-08-01 13:54 UTC, spencergilbert commented
> I hope you guys don't mind if I chime in here. I have been using the kafka source to read AEH for quite some time now. What is the advantage of this dedicated source compared to just providing a specific guide? Or in other words: should I switch my existing configs when this lands?
> 
> I quickly skimmed the code and I think no specific librdkafka options are set. I have been using the ones specified by Microsoft here: https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/CONFIGURATION.md#librdkafka-configuration-properties
> 
> I honestly don't know whether they make any real difference though.

Of course we don't mind 😄 it's definitely an ease of config situation. If the `kafka` source is working fine for you there isn't any "secret sauce" in the new source. Think of it more like "syntactic sugar" for the config.

@StephenWakely, I'm not sure we knew they had recommended values for `librdkafka` - I think that gives a good reason to expose that in the config (if not default to them).

2022-08-01 14:38 UTC, jszwedko commented
@jeromekleinen-kbc to add on to what Spencer said, you can find some more detail in: https://github.com/vectordotdev/vector/blob/master/docs/USER_EXPERIENCE_DESIGN.md#source--sink-boundaries. Essentially having a dedicated sink helps with discoverability and streamlines user configuration.

2022-08-09 10:05 UTC, StephenWakely commented
The Kafka protocol doesn't work with the Azure basic tier. A proper solution needs to use the AMQP protocol, which we will look at doing in due course. Closing this.

2022-08-09 10:05 UTC, closed without merging