feat(parsing): function to parse aws classic load balancer logs
vectordotdev/vector pull request #13974
Opened 2022-08-15 12:56 UTC by carnei-ro

2022-10-12 15:32 UTC, StephenWakely requested changes
Hi, many thanks for this. Sorry for the delay in getting it reviewed.

I have one comment around reusing some code, and it needs a conflict with master resolved.

2022-10-12 15:32 UTC, StephenWakely commented on lib/vrl/stdlib/src/parse_aws_clb_log.rs
> +    }
These macro rules appear to be the same as those in `parse_aws_alb_log`, would it be possible to move those into a shared file and reuse them here?

2022-10-12 16:29 UTC, StephenWakely commented
@carnei-ro Could you hold for a bit on making these changes. We are currently discussing amongst ourselves if there is a better way we can manage all these specific parsing functions, so not sure at present if we will move forward with this..

2023-02-22 15:11 UTC, fuchsnj commented
Hey @carnei-ro, we discussed this with the team and decided we can move forward with the parsing function as-is. Are you still available to finish this up?

2023-03-28 15:41 UTC, fuchsnj commented
I apologize for the inconvenience, but VRL has been moved to a [separate repo](https://github.com/vectordotdev/vrl), and this PR will need to be moved over there.

2023-03-28 15:41 UTC, closed without merging