fix(aws_s3 source): Handle s3:TestEvent and drop it
vectordotdev/vector pull request #14572
Opened 2022-09-26 13:57 UTC by bencord0

https://github.com/vectordotdev/vector/discussions/14047

Vector currently fails to process test events created by S3. These are benign events that can be ignored to prevent serde parser failures.

2022-09-26 16:54 UTC, spencergilbert requested changes
Thanks for the contribution, looks like a straightforward fix for an annoying issue.

2022-09-26 16:54 UTC, spencergilbert commented on src/sources/aws_s3/sqs.rs
> +                debug!(message = "Found S3 Test Event", ?message.message_id);
```suggestion
                debug!(?message.message_id, message = "Found S3 Test Event.");
```

Passes the existing `check-events` scripts, and re-ordered to pass an upcoming change to the script.

2022-09-26 16:54 UTC, spencergilbert commented on src/sources/aws_s3/sqs.rs
> +// https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-enable-disable-notification-intro.html
I'm not entirely sure how this link relates to the test event - it seems like the `notification-content-structure.html` below also covers this event. Perhaps that comment should just get pulled up to the new `Enum`?

2022-09-27 13:03 UTC, bencord0 commented
Thanks for the review @spencergilbert, I've updated the patch with both of those changes

2022-09-27 15:27 UTC, spencergilbert approved these changes

2022-09-27 20:35 UTC, jszwedko approved these changes
Looks good, thanks for this @bencord0 !

2022-09-28 08:45 UTC, bencord0 commented
I've pushed a change based on the failed [`make check-fmt`](https://github.com/vectordotdev/vector/actions/runs/3135816207/jobs/5094336163) that adjusts the formatting.

2022-09-28 13:03 UTC, spencergilbert commented
🤔 looks like there's still a `cargo fmt` issue?

2022-09-29 11:10 UTC, spencergilbert approved these changes

2022-09-29 12:37 UTC, merged