enhancement(observability): Track total allocations/deallocations
vectordotdev/vector pull request #15393
Opened 2022-11-29 19:57 UTC by arshiyasolei

Add support for tracking the accumulated memory deallocations and allocations per component.

2022-11-30 21:02 UTC, tobz requested changes
Just noted a small change that needs to be made but otherwise looks good to me. 👍🏻

2022-11-30 21:18 UTC, jszwedko commented on src/internal_telemetry/allocations/mod.rs
> +                            "component_id" => group_info.component_id.clone());
👍 I was about to say the same thing, these seem like they should be counters.

2022-11-30 22:17 UTC, arshiyasolei commented on src/internal_telemetry/allocations/mod.rs
> +                            "component_id" => group_info.component_id.clone());
There currently is an issue with counters resetting to zero when there's no reporting.

2022-12-01 14:28 UTC, tobz commented on src/internal_telemetry/allocations/mod.rs
> +                            "component_id" => group_info.component_id.clone());
Counters don't display cumulatively on Datadog, so you should only expect to see spikes in the graphs when an update is emitted, which is consistent with what you're seeing.

2022-12-01 18:30 UTC, tobz approved these changes
Yeah, this makes sense to me.

Saw what looked like a small jump in the overhead to around -10% at worst, which is unfortunate... but I imagine we can claw that back with some profiling/data locality refactoring.

2022-12-01 18:32 UTC, arshiyasolei commented
Yeah I think that 10% regression was due to not being updated w/ the main branch aha

2022-12-01 21:26 UTC, merged