docs(influxdb_logs sink): autogen docs
vectordotdev/vector pull request #16356
Opened 2023-02-07 22:45 UTC by davidhuie-dd

Closes #16021

2023-02-07 23:48 UTC, spencergilbert requested changes
There were a couple of examples dropped (ex `token` `username`) but I'd approve it without those added since they're so simple.

2023-02-07 23:48 UTC, spencergilbert commented on src/sinks/influxdb/logs.rs
>      #[configurable(deprecated)]
```suggestion
    #[configurable(deprecated = "This field is deprecated, and `measurement` should be used instead.")]
```

2023-02-08 23:02 UTC, spencergilbert approved these changes

2023-02-08 23:09 UTC, spencergilbert commented on src/sinks/influxdb/logs.rs
>      #[configurable(deprecated)]
I betrayed you! Didn't format it properly 😭

2023-02-08 23:48 UTC, neuronull approved these changes

2023-02-08 23:48 UTC, neuronull commented on src/sinks/influxdb/logs.rs
> +    #[configurable(metadata(docs::examples = "http://localhost:8086/"))]
nit (I know it was this way in the existing docs)

```suggestion
    #[configurable(metadata(docs::examples = "http://localhost:8086"))]
```

2023-02-13 18:23 UTC, merged