fix(redis source): fix high cpu on redis intermittent connection issues
vectordotdev/vector pull request #16518
Opened 2023-02-20 12:56 UTC by hargut

error scenario:
- vector starts and successfully initializes the redis source
- the connection experiences issues
- which lead to high CPU usage (>1 core)

the fix introduces a backoff at 100ms in case of a `RedisError::ErrorKind::IoError` to remediate the high CPU issue during described scenario

https://github.com/vectordotdev/vector/issues/16492

2023-02-20 13:36 UTC, StephenWakely approved these changes
Nice. Thanks for this. I'm wondering if an exponential backoff would be even more useful, but this will at least improve the situation.

2023-02-20 17:43 UTC, hargut commented
I've updated it to an exponential backoff with a cap at 1000ms and fixed the fmt issue.

2023-02-22 10:15 UTC, StephenWakely requested changes
Thanks for making that change, I think just a couple of minor tweaks and we should be good.

2023-02-22 10:15 UTC, StephenWakely commented on src/sources/redis/list.rs
> +async fn backoff_exponential(exp: &u32) {
This doesn't need to be a reference.

```suggestion
async fn backoff_exponential(exp: u32) {
```

2023-02-22 10:15 UTC, StephenWakely commented on src/sources/redis/list.rs
> +    let ms = if *exp <= 9 { 2_u64.pow(*exp) } else { 1000 };
Can we start at 32 and move up from there?

```suggestion
    let ms = if exp <= 4 { 2_u64.pow(exp + 5) } else { 1000 };
```

2023-02-22 11:55 UTC, hargut commented
Hi @StephenWakely,

thank you for the review & suggestions. Added it to the PR.

2023-02-23 13:31 UTC, merged