chore(core): Migrate `LogSchema` `timestamp` to new lookup code
vectordotdev/vector pull request #16839
Opened 2023-03-17 17:44 UTC by fuchsnj

:construction: Work in progress :construction: 

fixes https://github.com/vectordotdev/vector/issues/16834

The `LogSchema` timestamp key was previously a `String`, which makes it very easy to mis-use it. It's not obvious that it can be optional (by using an empty string, or technically any invalid path). This has been migrated to a typed path which should help prevent these types of problems from happening again.

2023-03-21 15:27 UTC, spencergilbert requested changes
Caught a couple of things 😄

2023-03-21 15:27 UTC, spencergilbert commented on lib/codecs/src/decoding/format/gelf.rs
> +        if let Some(timestamp_key) = log_schema().timestamp_key() {
This conditional gets dropped again when/if we remove the global log schema?

2023-03-21 15:27 UTC, spencergilbert commented on src/sinks/aws_kinesis/streams/integration_tests.rs
> +#![allow(warnings)]
```suggestion
```

2023-03-21 15:27 UTC, spencergilbert commented on src/sinks/aws_kinesis/streams/integration_tests.rs
> +    // = random_lines_with_stream(100, 11, None);
```suggestion
```

2023-03-21 15:27 UTC, spencergilbert commented on src/sinks/aws_kinesis/streams/integration_tests.rs
> +    // assert_eq!(output_lines, input_lines)
```suggestion]
```

2023-03-21 17:10 UTC, fuchsnj commented on scripts/integration/aws/test.yaml
> +test_filter: ::aws_kinesis::streams
oops, yea the integration changes shouldn't have been included here

2023-03-21 17:22 UTC, spencergilbert commented
Did you intentionally leave that kinesis integration test commented out again?

2023-03-21 17:33 UTC, fuchsnj commented
> Did you intentionally leave that kinesis integration test commented out again?

Yes, that was just testing I was doing locally. It shouldn't have been included in this PR since it's completely unrelated.

2023-03-21 17:37 UTC, spencergilbert approved these changes

2023-03-22 11:24 UTC, StephenWakely approved these changes
Looks good to me.

2023-03-22 14:35 UTC, merged