fix(incoming.rs): Upgrade Mozilla TLS standard to v5
vectordotdev/vector pull request #17191
Opened 2023-04-21 05:30 UTC by gaby

Currently Vector is accepting connections via TLS1.0 and 1.1, and doesn't support TLS1.3

The current core incoming SslAcceptor is still using the old v4, updating to v5 will allow TLS1.2 to becoming the min and TLS1.3 while also disabling TLS1.0, 1.1 which are big security issue right now for some deployments as pointed out by me in #11959 

Docs: https://docs.rs/openssl/latest/openssl/ssl/struct.SslAcceptor.html#method.mozilla_intermediate_v5

There's also a comment in the openssl source saying the v4 method will get removed in the next major version: https://docs.rs/openssl/latest/src/openssl/ssl/connector.rs.html#277

2023-04-21 17:25 UTC, bruceg requested changes
Since this has the (admittedly small) potential of  breaking existing uses of Vector, this will need to go through [the deprecation process](https://github.com/vectordotdev/vector/blob/master/docs/DEPRECATION.md). So, this would involve starting with adding an option to allow for opting in to this new behavior, followed by or concurrent with a deprecation notice in the documentation regarding this.

2023-04-21 21:28 UTC, gaby commented
@bruceg Unless someone from the Vector team can make those changes, I will have to close this. I only know very basic Rust.

2023-04-23 14:53 UTC, gaby commented
@bruceg The ietf deprecated TLS1.0/1.1 back in Winter 2021, browsers dont even support it anymore since 2020. Does `Vector` really need to go through a deprecation process for something that was deprecated 1.5 years ago?

Source:
- https://datatracker.ietf.org/doc/rfc8996/
- https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls
- https://security.googleblog.com/2018/10/modernizing-transport-security.html
- https://webkit.org/blog/8462/deprecation-of-legacy-tls-1-0-and-1-1-versions/

2023-04-24 15:55 UTC, bruceg commented
@gaby I agree, it _should_ be safe to make this change, particularly since TLS 1.2 was introduced about 15 years ago. All service providers worth paying for will be supporting 1.2 if not 1.3 already. However, since Vector is an aggregator that may receive data from a wide variety of kinds of sources, including potentially old IoT devices, we need to at least provide the option to maintain backwards compatibility [by providing an option to set the acceptor](https://github.com/vectordotdev/vector/issues/14832).  We would appreciate a PR that follows that path if you are still willing.

2023-04-26 01:27 UTC, gaby commented
@bruceg That makes sense, I will try to see if I can figured out how to implement this. I honestly have 0 Rust experience :-)

2023-04-26 19:19 UTC, bruceg commented
> @bruceg That makes sense, I will try to see if I can figured out how to implement this. I honestly have 0 Rust experience :-)

Understood. Let us know how you make out and if you have any questions so we don't end up duplicating your work.

Since the solution for this is going to take a different path, I'm also closing this PR in anticipation of another solution. Feel free to reopen this if it makes more sense for you to continue the work here.

2023-04-26 19:19 UTC, closed without merging