chore: Add UX note about encoding of log_schema keys
vectordotdev/vector pull request #17266
Opened 2023-05-01 21:50 UTC by jszwedko

Will need to be updated when log namespacing is released.

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

2023-05-01 22:01 UTC, neuronull approved these changes

2023-05-01 22:57 UTC, spencergilbert requested changes

2023-05-01 22:57 UTC, spencergilbert commented on docs/USER_EXPERIENCE_DESIGN.md
> +a "hostname", it should fetch it from the log event using `log_schema.host_key` and place it in the
Actually it should use these helpers https://github.com/vectordotdev/vector/blob/7570bb31e2f471e3ff8bc818c24e9bde3090818c/lib/vector-core/src/event/log_event.rs#L433

2023-05-16 20:07 UTC, spencergilbert approved these changes
This would also need to be changed depending on the outcome of our RFC/discussion of the `datadog_logs` sink

2023-05-16 20:19 UTC, merged