feat(new avro decoder): new `avro` decoder
vectordotdev/vector pull request #17521
Opened 2023-05-27 08:07 UTC by cameronbraid

**Apache Avro Message Format Decoder Implementation**

This repository features an  implementation of a decoder for the Apache Avro message format. Key features of this implementation include:

- **Single `schema` operation**: The decoder operates on a single `schema` that is predefined within the configuration.

- **Support for `strip_schema_id_prefix`**: This feature is incredibly handy when working with Kafka messages that incorporate a 'magic byte' and a schema id into the message bytes.

Currently, we're working on documentation to detail the configuration of the codec. Unfortunately, we haven't been able to locate any existing decoder configuration documentation to reference. Should anyone possess familiarity with this topic, your help would be most welcome.

2023-08-02 16:20 UTC, pront requested changes
Thank you @cameronbraid for submitting this PR!

I did a first review pass, left some comments. I will do another pass as soon as you push an update, thanks again.

2023-09-15 09:00 UTC, WarmSnowy commented
hi,@cameronbraid. Is this PR still being actively developed?

2023-09-21 16:56 UTC, aristot3 commented
+1, I'd like to implement this. Is there any doc that shows what to write in vector.toml to deserialize AVRO from a Kafka source ?
Thanks a lot @cameronbraid

2023-09-21 17:25 UTC, pront commented
> +1, I'd like to implement this. Is there any doc that shows what to write in vector.toml to deserialize AVRO from a Kafka source ? Thanks a lot @cameronbraid

Hi @aristot3, happy to answer any questions that come up.

I do not have an example with a Kafka source, you might be able to use the following as a starting point.

### vector.toml
```toml
data_dir = "path/to/local/dir"

[sources.my_file]
type = "file"
include = ["path/to/local/dir/avro.txt"]
read_from = "beginning"

[sources.vector_metrics]
type = "internal_metrics"

[transforms.extract_message]
type = "remap"
inputs = ["my_file"]
source = """
    . = parse_json!(.message)      
"""

[sinks.my_console_sink]
type = "console"
inputs = ["extract_message"]
[encoding.avro]
codec = "avro"
schema = "{ \"type\": \"record\", \"namespace\": \"com.example\", \"name\": \"avrotest\", \"fields\": [ { \"name\": \"time\", \"type\": \"string\" }, { \"name\": \"name\", \"type\": \"string\" }, { \"name\": \"color\", \"type\": \"string\" } ] }"
```

### avro.txt
```
{"time":"2023-08-09_09:26:35","name":"PVWhiK0cN4tMDGV90pxRKOCfacuCaN5hMg50PiHqYwggLRRtvItzmk6BKjXZko2SwqtXlnHqvPR6jjuC","color":"7xozv7Br9Rxbk3Lb1bZm7H8MOreezUsJviCxTJAziqpOtNuL7Sr6v0Ylt375HcxZDo5sJG2FyRm45WHI"}
{"time":"2023-08-09_09:26:35","name":"PVWhiK0cN4tMDGV90pxRKOCfacuCaN5hMg50PiHqYwggLRRtvItzmk6BKjXZko2SwqtXlnHqvPR6jjuC","color":"7xozv7Br9Rxbk3Lb1bZm7H8MOreezUsJviCxTJAziqpOtNuL7Sr6v0Ylt375HcxZDo5sJG2FyRm45WHI"}
{"time":"2023-08-09_09:26:35","name":"PVWhiK0cN4tMDGV90pxRKOCfacuCaN5hMg50PiHqYwggLRRtvItzmk6BKjXZko2SwqtXlnHqvPR6jjuC","color":"7xozv7Br9Rxbk3Lb1bZm7H8MOreezUsJviCxTJAziqpOtNuL7Sr6v0Ylt375HcxZDo5sJG2FyRm45WHI"}
```

2023-09-21 17:34 UTC, aristot3 commented
@pront @WarmSnowy thank you so much for your answers, I wasn't excepting such a quick help ! I'm going to try this tomorrow, I'd really like to get rid of my big Logstash cluster

2023-09-21 17:46 UTC, WarmSnowy commented
@cameronbraid @pront Hi, I resolved some above review comments, could I contribute it? https://github.com/WarmSnowy/vector/tree/avro-dev

2023-09-21 17:59 UTC, pront commented
> @cameronbraid @pront Hi, I resolved some above review comments, could I contribute it? https://github.com/WarmSnowy/vector/tree/avro-dev

@WarmSnowy all contributions are very welcome. Feel free to submit a new PR based on @cameronbraid's work. To avoid duplicate work, I would recommend syncing with @aristot3.

2023-09-21 18:07 UTC, WarmSnowy commented
Thanks. I'll make a new PR.

2023-09-21 18:27 UTC, WarmSnowy commented
Hi @cameronbraid  @pront @aristot3, I submitted a new PR #18636 base on this patch, could you help review it?

2023-09-21 23:48 UTC, cameronbraid commented
Hi, sorry I have been out of the loop for a bit.  Had other priorities.

Looks good to see some others helping with this effort :)

I was thinking that a followup to this 'static' schema would be to use something like https://github.com/gklijs/schema_registry_converter to grab the schema from a registry

Good work people !

2023-09-22 02:13 UTC, WarmSnowy commented
Thanks for your idea. 

AFAIK other sources (like apache pulsar) may also need avro decoder, to introduce an option which allow auto grabing schema from register is more universal. Or we can introduce a new confluent codec for [confluent wire format](https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/index.html#wire-format)   later?

2023-09-22 08:33 UTC, aristot3 commented
> > +1, I'd like to implement this. Is there any doc that shows what to write in vector.toml to deserialize AVRO from a Kafka source ? Thanks a lot @cameronbraid
> 
> 
> 
> I'm working on pulsar with avro, hope my demo can help you.
> 
> ```
> 
> [sources.pulsar]
> 
> type         = "pulsar"
> 
> endpoint     = "pulsar://localhost:6650"
> 
> topics       = ["persistent://public/default/topic1"]
> 
> consumer_name = "vector"
> 
> subscription_name = "vector2"
> 
> 
> 
> [sources.pulsar.decoding]
> 
> codec = "avro"
> 
> avro.schema = """
> 
> {
> 
>     "type": "record",
> 
>     "name": "test",
> 
>     "fields": [
> 
>         {"name": "a", "type": "long", "default": 42},
> 
>         {"name": "b", "type": "string"}
> 
>     ]
> 
> }
> 
> """
> 
> avro.strip_schema_id_prefix = false
> 
> 
> 
> [sinks.out]
> 
> inputs = ["pulsar"]
> 
> type = "console"
> 
> encoding.codec = "json"
> 
> ```



This seems to work very well on my lab. I'll try to get my hands on the code this weekend

2023-09-22 08:40 UTC, WarmSnowy commented
> > > +1, I'd like to implement this. Is there any doc that shows what to write in vector.toml to deserialize AVRO from a Kafka source ? Thanks a lot @cameronbraid
> > 
> > 
> > 
> > I'm working on pulsar with avro, hope my demo can help you.
> > 
> > ```
> > 
> > [sources.pulsar]
> > 
> > type         = "pulsar"
> > 
> > endpoint     = "pulsar://localhost:6650"
> > 
> > topics       = ["persistent://public/default/topic1"]
> > 
> > consumer_name = "vector"
> > 
> > subscription_name = "vector2"
> > 
> > 
> > 
> > [sources.pulsar.decoding]
> > 
> > codec = "avro"
> > 
> > avro.schema = """
> > 
> > {
> > 
> >     "type": "record",
> > 
> >     "name": "test",
> > 
> >     "fields": [
> > 
> >         {"name": "a", "type": "long", "default": 42},
> > 
> >         {"name": "b", "type": "string"}
> > 
> >     ]
> > 
> > }
> > 
> > """
> > 
> > avro.strip_schema_id_prefix = false
> > 
> > 
> > 
> > [sinks.out]
> > 
> > inputs = ["pulsar"]
> > 
> > type = "console"
> > 
> > encoding.codec = "json"
> > 
> > ```
> 
> 
> 
> This seems to work very well on my lab. I'll try to get my hands on the code this weekend 

I submitted a new PR #18636 base on this，you can check it to avoid duplicate work. @aristot3

2023-09-22 14:21 UTC, pront commented
Moved to https://github.com/vectordotdev/vector/pull/18636

2023-09-22 14:21 UTC, closed without merging