feat(opcua source): add initial OPCUA source
vectordotdev/vector pull request #17594
Opened 2023-06-04 20:44 UTC by simonhoss

Hey guys

This is my first try adding OPCUA as source to vector ecosystem. Its my first rust pr ever, so any feedback is appreciated!

According ticket: #17593

2023-06-30 19:45 UTC, jszwedko commented
Apologies for the delay here @simonhoss ! We'll be reviewing this soon. Thanks for the contribution!

2023-07-31 14:52 UTC, dsmith3197 commented
Hi @simonhoss, thank you for the contribution!

Just an FYI, per our [docs](https://github.com/vectordotdev/vector/blob/master/CONTRIBUTING.md#new-sources-sinks-and-transforms), we will begin with completing that checklist prior to reviewing the code. No need to write up answers to the checklist questions at this stage, I will inquire about anything in this PR's comment thread.

As for now, I'm curious about two things:

> If this would be integrated we would be able to collect metrics and logs direct from machines without any converter.

Could you elaborate on your current use case? What converter do you use? Is this being used in an industrial or consumer setting?

>  (From the checklist) Is the contributor committed to maintaining the integration if it is accepted?

Would you be willing to maintain this source if it is accepted?

2023-08-03 13:43 UTC, simonhoss commented
> Could you elaborate on your current use case? What converter do you use? Is this being used in an industrial or consumer setting?

OPC/UA is an industrial protocol and used in machine communication. Our use case is, that we want to grab machine data and forward it to a broker or directly save it in a database, for example an Influx. As an info at the moment it only grabs metrics and more specific floating metrics. I just wanted to have a starting point.

> Would you be willing to maintain this source if it is accepted?

Sure. We have some more use case which we want to extend as well.

2023-08-09 13:26 UTC, dsmith3197 commented
@simonhoss I have some good news, we've received the green light to add this source to Vector, and I will begin reviewing the code shortly.

2023-08-11 21:17 UTC, dsmith3197 requested changes
Thank you again for the contribution and for taking the time to learn rust! I'm impressed.

I took a preliminary look through this and left some comments, primarily focused on the configuration. I need some more time to throughly review the `opcua_source()` and related functions.  As you probably encountered, the `opcua` crate doesn't play too nicely with vector's tokio runtime because the crate exposes a synchronous API but uses tokio internally. To be clear, I don't see anything that would prevent us from merging this, but just need some time to think through it.

2023-08-12 20:03 UTC, simonhoss commented
Thanks a lot. I will work on beginning next week!

2023-09-17 20:23 UTC, simonhoss commented on src/sources/opcua/mod.rs
> +            product_uri: "urn:SimpleClient".to_string(),
Based on the original client example, it must not:

https://github.com/locka99/opcua/blob/master/samples/simple-client/src/main.rs#L56

2023-09-17 21:10 UTC, simonhoss commented on src/sources/opcua/mod.rs
> +    /// The OPC/UA URL to connect to.
I corrected it

2023-09-17 21:12 UTC, simonhoss commented on src/sources/opcua/mod.rs
> +    #[configurable(metadata(docs::examples = "product_uri"))]
This is more for identifying. https://reference.opcfoundation.org/Core/Part4/v104/docs/7.1

2023-09-17 21:52 UTC, simonhoss commented
@dsmith3197 Sorry for my delay. Would you mind checking the PR again?

2023-10-13 06:29 UTC, closed without merging

2023-10-19 14:19 UTC, dsmith3197 commented
Hey @simonhoss, my apologies for not getting back to this in a timely manner. Would you still be interested in pushing this forward if we review it?