jszwedko/revive 14528
vectordotdev/vector pull request #18151
Opened 2023-08-03 20:56 UTC by jszwedko

- Convert tags into attributes.
- Decompose metric into parts to reuse tags instead of cloning.
- Remove unnecessary blocks.
- Set metric type.
- Fix field name typo.
- Remove unnecessary brackets.
- Cargo fmt.
- Update src/sinks/new_relic/model.rs
- Update src/sinks/new_relic/model.rs
- Fix typo.
- Add tests for newly supported metrics.
- Simplify metric type cases.
- Cargo fmt.
- Update to handle new tag model

2023-08-03 23:25 UTC, bruceg reviewed
I have a couple of suggestions for code ordering but otherwise this looks reasonable.

2023-08-03 23:25 UTC, bruceg commented on src/sinks/new_relic/model.rs
> +                });
I would suggest moving this down to where `attr` is actually used. This avoids doing the work to set up the attributes if they are not used, as well as allowing for simplifications of the coding.

2023-08-03 23:25 UTC, bruceg commented on src/sinks/new_relic/model.rs
>                      }
Similarly, I would suggest moving this up early in this block so that it can break out before doing any unnecessary work.

2023-08-07 18:23 UTC, dsmith3197 requested changes
I think this PR incorrectly claims to close https://github.com/vectordotdev/vector/issues/13902.

@jszwedko Let me know if you want me to take over this PR. Happy to help out if so :)

2023-08-07 18:23 UTC, dsmith3197 commented on src/sinks/new_relic/model.rs
> +                            continue;
On further investigation, the [New Relic docs state](https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/cumulative-metrics/#explained) that cumulative counters can be given the `cumulativeCount` type and will be incrementalized on the server side.

2023-08-10 15:11 UTC, bruceg reviewed
I think I missed seeing a couple things on my previous review. Comments below.

2023-08-10 15:11 UTC, bruceg commented on src/sinks/new_relic/model.rs
> +                    metric_array.push(metric_data);
It appears exactly one element is pushed per input element. Could this be a `map` then?

2023-08-22 21:15 UTC, dsmith3197 commented on src/sinks/new_relic/model.rs
>          }
Here and elsewhere, I'm not a fan of emitting these events within a `TryFrom` implementation but it made the most sense given the existing implementation. I'm happy to consider alternatives if others have strong opinions.

2023-08-22 21:16 UTC, dsmith3197 commented
@bruceg could you take another look? I addressed your feedback and added `ComponentEventsDropped` events where relevant.

2023-09-01 00:01 UTC, bruceg approved these changes
I think I need to apologize. Very Canadian, I'm sure. When I first read this PR, I misread the insert inside the conditional `if let Some …` as being outside the conditional, making it a straight one-to-one map, hence my comment. Now that you followed my suggestions and contorted it into a `.filter_map` I see my mistake. It probably works out to the same code gen after optimization, so I am going to approve it as-is just to avoid adding frustration.

2023-09-12 14:31 UTC, dsmith3197 commented
I'll address https://github.com/vectordotdev/vector/issues/13902 in another PR.

2023-09-12 14:33 UTC, dsmith3197 approved these changes

2023-09-12 16:05 UTC, merged