docs: add timestamp comparison example
vectordotdev/vector pull request #19266
Opened 2023-11-30 12:40 UTC by maksimtor

Add one example of timestamp comparison due to recent changes in vrl.

2023-11-30 15:13 UTC, pront approved these changes
👍

2023-11-30 16:11 UTC, jhgilbert approved these changes

2023-11-30 17:02 UTC, pront requested changes

2023-12-01 10:34 UTC, pront approved these changes

2023-12-13 15:39 UTC, merged