feat: pub prometheus sink configs
vectordotdev/vector pull request #19540
Opened 2024-01-08 11:42 UTC by suikammd

close issue #19517

2024-01-09 13:54 UTC, StephenWakely commented
@suikammd I think CI is exposing further errors to the rust-doc generation due to making these fields public. Would you be able to `cd rust-doc; make docs` and have a look at the errors it is now raising? It's unlikely to be caused by the changes you are making, so if you have any questions on how to fix them let me know.

2024-01-10 04:08 UTC, suikammd commented
@StephenWakely I find we should use vector_core in dev dependencies. After add this dependency, `make docs` passed.

You may check the new commit. thx!

2024-01-10 04:18 UTC, suikammd commented
@StephenWakely  I find we should add vector_core in dependencies. After add this dependency, `make docs` passed.
It is wired that add dependency to dependencies since we do not need it to build vector crate. I tried add this dependency to dev-dependencies, it doesn't work like described in this [link](https://github.com/rust-lang/cargo/issues/3475).

You may check the new commit. thx!

2024-01-10 18:33 UTC, pront approved these changes

2024-01-11 10:07 UTC, StephenWakely requested changes
@suikammd The error is because those symbols are being imported into Vector via `vector_lib::sink::VectorSink`. So rather changing Vector to import `vector_core`, can you update the links to point to `vector_lib`. You could probably remove the path altogether since the compiler should know where to find it:

```
//! Contains the [`VectorSink`] instance that is responsible
```

If you feel inclined could you change this comment:

```
//! The Prometheus Remote Write [`vector_core::sink::VectorSink`]
```

to just say


```
//! The Prometheus Remote Write sink
```

It doesn't really make sense to link to the trait in the comment there anyway.

2024-01-12 09:38 UTC, StephenWakely requested changes

2024-01-12 09:38 UTC, StephenWakely commented on src/sinks/prometheus/remote_write/mod.rs
> +//! The Prometheus Remote Write.
```suggestion
//! The Prometheus Remote Write sink.
```

2024-01-12 09:38 UTC, StephenWakely commented on src/sinks/prometheus/remote_write/mod.rs
>  //! for taking a stream of [`vector_core::event::Event`] and forwarding
```suggestion
//! for taking a stream of [`Event`] and forwarding
```

2024-01-15 16:03 UTC, StephenWakely approved these changes

2024-01-15 17:18 UTC, merged