fix(observability): propagate tracing span context in stream sink request building
vectordotdev/vector pull request #19712
Opened 2024-01-25 22:30 UTC by neuronull

Currently any vector logs or internal metrics that arise during the request building of stream sinks are missing automatic component tags.

This was discovered while implementing a sink validator for the component validation framework, for the internal metric  `component_discarded_events_total` (https://github.com/vectordotdev/vector/issues/16847)

2024-01-25 22:41 UTC, dsmith3197 approved these changes
nice find!

2024-01-25 23:04 UTC, jszwedko commented on changelog.d/19712_propagate_tracing_span_context_stream_sink_request_building.fix.md
> +Vector logs and internal metrics emitted while in the context of stream sink request building, now correctly contain the component's automatic tags (`component_kind`, `component_type`, `component_id`
I don't think a user will know what "stream sink request building" is or how that affects them. I would say something like:

The following metrics now correctly have the `component_kind`, `component_type`, and `component_id` tags:

- X
- Y

For sinks:

- A
- B
- C

2024-01-25 23:04 UTC, jszwedko requested changes
Marking as request changes just to avoid queuing until my comment is resolved.

Good find though!

2024-01-25 23:09 UTC, bruceg approved these changes

2024-01-26 00:29 UTC, jszwedko approved these changes
Perfect, thank you for updating the changelog!

2024-01-26 21:30 UTC, merged