[wip] Fixing bug - set missing in log-to-metric transform
vectordotdev/vector pull request #20228
Opened 2024-04-03 01:20 UTC by pabloem

2024-04-04 19:12 UTC, tobz requested changes
Thanks for your contribution here. 👍🏻 

As far as adding a test for it, the `testing` folder is actually meant simply to hold Vector configurations and test case documentation used when running tests _manually_.

You'll want to to create a new unit test in `src/transforms/log_to_metric.rs` in this case.

2024-04-04 19:47 UTC, jszwedko commented
There are also high-level behavior tests that run here: https://github.com/vectordotdev/vector/tree/master/tests/behavior/transforms. I agree that a unit test seems the most appropriate for this change though.

2024-04-05 13:06 UTC, pabloem commented
okay I added a test case. @tobz - let me know if that looks good.

Once we merge, can you also let me know in which release of vector the PR would land?

2024-04-05 14:12 UTC, jszwedko commented
> Once we merge, can you also let me know in which release of vector the PR would land?

It would be in v0.38.0 currently scheduled for May 7th. It'll be in the nightly builds earlier though if you want to try it out.

2024-04-05 21:41 UTC, jszwedko reviewed
Thanks for the test! Do you mind adding a changelog fragment describing the change too? See https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md

2024-04-06 03:00 UTC, pabloem commented
> Thanks for the test! Do you mind adding a changelog fragment describing the change too? See https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md

added! thanks!

2024-04-08 14:46 UTC, jszwedko reviewed
Thanks @pabloem! Just one comment about the changelog, but otherwise this looks good.

2024-04-08 14:46 UTC, jszwedko commented on changelog.d/20228_fix-log-to-metric-set-supported.fix.md
> +author: Pablo E.
```suggestion
author: pabloem
```

2024-04-08 14:46 UTC, jszwedko commented on changelog.d/20228_fix-log-to-metric-set-supported.fix.md
> +author: Pablo E.
This is actually expected to be a GH username.

2024-04-08 15:21 UTC, pabloem commented
Done thanks @jszwedko

2024-04-08 15:21 UTC, jszwedko approved these changes

2024-04-08 21:43 UTC, pabloem commented
looks like @tobz needs to change his review status? : ) - I don't know how to tell it to ignore the spellcheck on my username.

2024-04-08 21:54 UTC, jszwedko commented on changelog.d/20228_fix-log-to-metric-set-supported.fix.md
> +author: pabloem
```suggestion
authors: pabloem
```

Just realized this should be `authors:` which should also tell the spell checker to ignore the line.

2024-04-08 21:54 UTC, jszwedko commented
I'll let @tobz give this another 👍 in case there was something else he was expecting.

2024-04-09 13:53 UTC, tobz approved these changes

2024-04-09 15:53 UTC, merged