feat(loki sink): add support for structured metadata
vectordotdev/vector pull request #20576
Opened 2024-05-29 14:07 UTC by maxboone

See issue: https://github.com/vectordotdev/vector/issues/18876

Initial attempt on this, but seeking some feedback to wrap up. Mainly on these points:

- How do we want to make "structured metadata" configurable, currently I added the option to add a list of "keys" from the log but maybe using the exact same configuration representation as the labels is preferred?
- How can we deal with the change in protocol, as structured metadata is part of a newer protocol and this PR overrides the current proto.
- How extensive do we need tests to be, do we want ({ labels, no labels, dynamic labels} x { structured metadata, no structured metadata, dynamic structured metadata}) or is the addition of tests that only cover the new code sufficient?

2024-05-31 14:50 UTC, tobz commented
As far as the question around changes to the Protocol Buffers definition -- and I haven't look at the changes yet -- I _think_ it should be fine to use them as-is, so long as the changes as all backwards-compatible.

The addition of new fields to existing message types should be fine, as older servers should just ignore them, as far as I understand. I'm not sure how most gRPC server implementations handle requests for unknown gRPC _services_, though, if we're dealing with new RPC calls.

2024-05-31 15:17 UTC, tobz requested changes
Overall, it seems like the Protocol Buffers changes themselves should be safe and backwards-compatible, so it mostly boils down to documentation change cleanup and fixing some of the bugs that seem to be present.

2024-05-31 15:17 UTC, tobz commented on src/sinks/loki/config.rs
> +    /// Fields to add to structured metadata.
```suggestion
    /// Structured metadata that is attached to each batch of events.
    ///
    /// Both keys and values are templateable, which enables you to attach dynamic structured metadata to events.
    ///
    /// Valid metadata keys include `*`, and prefixes ending with `*`, to allow for the expansion of
    /// objects into multiple metadata entries. This follows the same logic as [Label expansion][label_expansion].
    ///
    /// [label_expansion]: https://vector.dev/docs/reference/configuration/sinks/loki/#label-expansion
```

2024-05-31 15:17 UTC, tobz commented on src/sinks/loki/sink.rs
> +            structured_metadata: Option::None,
Seems like you should actually be setting this to the `structured_metadata` field you've constructed above?

2024-07-10 04:06 UTC, kimxogus commented
Hi, is there any update in this PR? I'm waiting for this feature

2024-07-10 06:34 UTC, maxboone commented
> Hi, is there any update in this PR? I'm waiting for this feature

My bad, I had a lot of other work to attend to. Will pick this up Thursday.

2024-07-22 04:34 UTC, devkoriel commented
Hi there, it's great to see the progress on this PR for adding support for structured metadata in the Loki sink! The addition of structured metadata is a significant enhancement that will greatly benefit users.

I understand there are some concerns regarding the changes in protocol and the extent of testing required. While the changes in Protocol Buffers definitions seem to be safe and backwards-compatible, it is crucial to ensure thorough testing to cover various scenarios like labels, structured metadata, and dynamic structured metadata.

Addressing the feedback provided by tobz regarding documentation and code cleanup will further improve the overall quality of the implementation. Making the necessary adjustments in the code and documentation as suggested will help in achieving a more cohesive and maintainable solution.

Given the importance of this feature and the work put into it, I strongly encourage the team to review and merge this PR as soon as possible. This feature is eagerly awaited by users and will undoubtedly enhance the capabilities of the Loki sink in Vector. Let's work together to finalize the remaining tasks and get this valuable enhancement merged promptly. Thank you for your hard work on this PR!

2024-07-22 07:30 UTC, maxboone commented
@tobz thanks a ton for the feedback, I think I processed everything but this is a first real rust contribution for me so apologies for it being messy here and there. 

I kept the implementation as similar to the labels as I saw possible but that probably breaks any DRY criteria as it's basically the same code done over. Is it preferred if I refactor these into a single function e.g. `convertTemplatedMaptoVec` and call that from the respective functions?

2024-08-01 17:31 UTC, maxboone commented
@tobz I'll pick up the things that turn up from the CI tomorrow morning, if there's anything else lmk!

2024-08-15 14:17 UTC, maxboone commented
@tobz any news here, please lmk if I can do anything!

2024-08-15 14:25 UTC, tobz commented
@maxboone Apologies. I swore I had previously approved this, but it seems not!

LGTM overall, but it still needs a changelog entry. You can see the README for the changelog directory -- https://github.com/vectordotdev/vector/tree/master/changelog.d -- which explains what is required.

2024-08-15 14:25 UTC, tobz approved these changes

2024-08-15 14:39 UTC, maxboone commented
> LGTM overall, but it still needs a changelog entry.

@tobz Will do, thanks a ton for the review!

2024-08-16 05:50 UTC, maxboone commented
@tobz added the changelog entry, should be good to go :)

2024-08-16 18:05 UTC, maxboone commented
@pront @tobz I see some CI failing, is there something I can change / update (or extend the tests and run integration tests on my end)?

I haven't tested it against a local instance of Loki recently, if I need to set that up to ensure it works properly lmk!

2024-08-16 18:11 UTC, jszwedko commented
> @pront @tobz I see some CI failing, is there something I can change / update (or extend the tests and run integration tests on my end)?
> 
> I haven't tested it against a local instance of Loki recently, if I need to set that up to ensure it works properly lmk!

It looks like the integration tests are failing to compile. You should be able to get the same errors locally by running `make check-clippy`. You can also run the integration tests locally via `make test-integration-loki`.

2024-08-16 19:29 UTC, maxboone commented
> It looks like the integration tests are failing to compile. You should be able to get the same errors locally by running `make check-clippy`. You can also run the integration tests locally via `make test-integration-loki`.

Will do, will ping again if something pops up :)

2024-08-16 21:45 UTC, maxboone commented
I see some messages popping up from running clippy and the integration tests here. I really thought I had fixed those but reality seems different. I'll fix this in the morning (CEST) and poke again.

2024-08-16 22:29 UTC, jszwedko commented
> I see some messages popping up from running clippy and the integration tests here. I really thought I had fixed those but reality seems different. I'll fix this in the morning (CEST) and poke again.
> 
> It's mostly just the protobuf body that has changed and thus the unit test failing.

np! Happy to review again afterwards.

2024-08-17 06:45 UTC, maxboone commented
@jszwedko integration tests ran correctly with the latest changes, mainly added `#[serde(default)]` to `structured_metadata` in the LokiConfig, as the tests were failing on only the configuration and I personally would want to avoid adding a breaking change to existing configurations. 

Anyways, as far as I can replicate, the CI should succeed now!

2024-08-19 22:08 UTC, jszwedko commented
Great, thanks @maxboone ! Let me trigger CI here.

2024-08-28 06:24 UTC, kimxogus commented
👍

2024-08-28 13:40 UTC, miadabrin commented
@maxboone I think it just needs a docs regeneration using `make generate-component-docs` so that the tests pass

2024-08-28 14:33 UTC, maxboone commented
> @maxboone I think it just needs a docs regeneration using `make generate-component-docs` so that the tests pass

good call! will do in a minute

2024-09-02 02:27 UTC, kimxogus commented
@maxboone Could you run `make generate-component-docs`?

2024-09-03 19:47 UTC, jszwedko commented
I was in the area so I regenerated them.

2024-09-03 19:56 UTC, jhgilbert approved these changes

2024-09-03 19:59 UTC, maxboone commented
> good call! will do in a minute

Yeah, unfortunately WSL2 decided to drop out that afternoon after an non-downgradeable update. But it's working again - thanks @jszwedko for generating the docs <3

2024-09-03 21:47 UTC, merged