feat(#19183): make Chronicle namespace a templateable field
vectordotdev/vector pull request #20579
Opened 2024-05-29 18:38 UTC by ChocPanda

2024-05-29 18:41 UTC, ChocPanda commented
Hey @StephenWakely ,
I appreciated your help with https://github.com/vectordotdev/vector/pull/19398 and thought I'd try making the namespace a templateable field, as you suggested.
Would you mind taking a look, it feels like there should have been a simpler solution that didn't require making my own sink and partitioner

2024-05-29 20:21 UTC, brett0000FF approved these changes

2024-06-11 10:09 UTC, StephenWakely approved these changes
Looks good to me. A tiny niggle, but that's not really been introduced by this PR, so it's fine to go!

2024-06-11 10:25 UTC, StephenWakely commented on changelog.d/19183_templateable_chronicle_namespace.md
> +Make the Chronicle namespace a templatable field
This changelog needs to be named `changelog.d/19183_templateable_chronicle_namespace.enhancement.md`.

2024-06-11 10:26 UTC, StephenWakely requested changes
Can you run `chronicled_unstructured.rs` through `rustfmt`.

2024-06-12 17:34 UTC, StephenWakely approved these changes

2024-06-12 19:47 UTC, merged