enhancement(sinks): Retrying the HTTP sink in case of 404s and request timeouts
vectordotdev/vector pull request #21457
Opened 2024-10-08 20:20 UTC by noble-varghese

Adding the functionality to retry the log sending on getting a not found error(404) or a request timeout (408) from the HTTP sink. Since the defualt behavior is to drop the events during such events, this would affect the log propagation.

2024-10-08 22:31 UTC, pront commented
Hi @noble-varghese, thank you for the contribution. I think retrying for these codes is reasonable, I will take a closer look tomorrow. 

Note: Need to update the docs as well. See https://vector.dev/docs/reference/configuration/sinks/http/#retry-policy.

2024-10-09 03:32 UTC, noble-varghese commented
@pront Thanks for pointing it out ! I have updated the docs page and added unit tests on the http utils as well :)

2024-10-09 15:21 UTC, brett0000FF approved these changes

2024-10-09 20:10 UTC, pront requested changes
Hey @noble-varghese, I noticed the E2E test `http_to_http` [failed](https://github.com/vectordotdev/vector/actions/runs/11257844072/job/31314324260?pr=21457). This change actually is a breaking one. Since it is hard to evaluate the risk, it is better to err on the side of caution. After some discussion with the team, I created https://github.com/vectordotdev/vector/issues/21469 to layout a solution for this.

2024-10-09 21:03 UTC, pront commented
To unblock this PR, perhaps we can add 408 to the defaults? Still a breaking change, but seems desirable and low risk. cc @jszwedko

2024-10-30 15:15 UTC, pront commented on src/sinks/util/http.rs
> +            StatusCode::FORBIDDEN => RetryAction::Retry("request forbidden".into()),
```suggestion
            StatusCode::REQUEST_TIMEOUT => RetryAction::Retry("request timeout".into()),
```

2024-10-30 15:16 UTC, pront commented
I tried to push directly to the fork but I don't have write permissions.

2024-10-30 15:18 UTC, noble-varghese commented
> I tried to push directly to the fork but I don't have write permissions.

I will push those changes. Thanks !

2024-10-30 15:34 UTC, noble-varghese commented
@pront  Just curious to know, how do you run these tests on the local. It was taking me about 30-40mins for it to run. Is there a faster way ?

2024-10-30 15:44 UTC, jszwedko commented on changelog.d/21457_more_error_codes_on_http_sink.enhancement.md
> +The `http sink` will now retry requests when the status is 408(request timeout).
```suggestion
The `http sink` will now retry requests when the response is a request timeout (HTTP 408).
```

Small proofreading.

2024-10-30 17:23 UTC, jszwedko commented
> @pront Just curious to know, how do you run these tests on the local. It was taking me about 30-40mins for it to run. Is there a faster way ?

You could try `cargo test --no-default-features --features sinks-http`. This and other tips are mentioned here: https://github.com/vectordotdev/vector/blob/master/docs/DEVELOPING.md#tips-and-tricks

2024-10-31 20:12 UTC, pront commented
> > @pront Just curious to know, how do you run these tests on the local. It was taking me about 30-40mins for it to run. Is there a faster way ?
> 
> You could try `cargo test --no-default-features --features sinks-http`. This and other tips are mentioned here: https://github.com/vectordotdev/vector/blob/master/docs/DEVELOPING.md#tips-and-tricks

Thanks Jesse, very neat.

Also, I always run the following before pushing to the remote branch:

- cargo install -f --path vdev #cd to the repo root
- `cargo vdev fmt`
- `cargo vdev check rust --clippy`

2024-11-06 18:54 UTC, pront approved these changes

2024-11-07 00:15 UTC, merged