docs(vrl): add crc vrl function docs
vectordotdev/vector pull request #21924
Opened 2024-11-30 20:32 UTC by ivor11

## Summary

add docs for crc32 vrl function
https://github.com/vectordotdev/vrl/pull/1136 

## Change Type
- [ ] Bug fix
- [ ] New feature
- [x] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist
- [x] Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- [ ] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

## References

https://github.com/vectordotdev/vrl/issues/997

2024-12-05 01:07 UTC, jszwedko commented on website/cue/reference/remap/functions/crc32.cue
> +		Calculates a CRC32 of the `value`.
```suggestion
		Calculates a CRC32 of the string,`value`.
```

2024-12-05 01:07 UTC, jszwedko approved these changes

2024-12-05 16:21 UTC, pront requested changes
Waiting for this improvement: https://github.com/vectordotdev/vrl/pull/1136#discussion_r1866540541 (docs will have to be updated)

2025-01-10 16:55 UTC, pront approved these changes

2025-01-11 03:06 UTC, merged