feat(new sink): new `SignalFx` sink
vectordotdev/vector pull request #2562
Opened 2020-05-07 15:39 UTC by apestel

First attempt to implement a SignalFx sink.
(sorry, new to Vector, new to Rust :))

Ref #2561

2020-05-10 15:39 UTC, binarylogic commented
Hey @apestel, thanks for this! We'll get a review this week.

2020-05-11 17:45 UTC, bruceg requested changes
Thanks! This looks very good for a first submission. I have a few questions and change suggestions before this is ready to merge. I notice there aren't any tests. It would be good to have some assurances that this continues to do what it should once we accept it into the code base. Is there an emulator or similar that could be run from Docker to test against?

2020-05-11 17:45 UTC, bruceg commented on src/sinks/signalfx/metrics.rs
> +    //     ));
Can this remnant be removed? It doesn't seem to be adding anything here.

2020-05-11 17:45 UTC, bruceg commented on src/sinks/signalfx/metrics.rs
> +        self.last_sent_timestamp.store(now, Release);
This looks like a race condition. Should it use a loop around `compare_and_swap` or `compare_exchange` instead?
```rust
let mut now = Utc::now().timestamp();
while self.last_sent_timestamp.compare_and_swap(now, AcqRel) != now {
    now = Utc::now().timestamp();
}
```

2020-05-11 17:45 UTC, bruceg commented on src/sinks/signalfx/metrics.rs
> +    }
I'd prefer a match here, but that's a minor thing.

2020-05-11 17:45 UTC, bruceg commented on src/sinks/signalfx/metrics.rs
> +            };
I think this `match` could be replaced with `.unwrap_or_default()`.

2020-05-11 17:45 UTC, bruceg commented on src/sinks/signalfx/metrics.rs
> +        .collect::<Vec<_>>();
It looks like the inner vectors produced by this iterator are all either single elements or `None`. Do I see that right? If so, dropping the inner vector and the trailing `flatten()` seems the best route.

2020-05-13 08:17 UTC, xp-1000 commented on .meta/sinks/signalfx_metrics.toml.erb
> +<%= render("_partials/descriptions/_signalfx.toml") %>
SignalFx Logs does not exist yet but this will be relevant to add support for it when the product will be available (probably starts in 2021)

2020-07-21 03:58 UTC, binarylogic commented
Hi @apestel, thanks for takign the time to do this. I'm going to close this given the inactivity. Please feel free to reopen if you'd like to address the comments above. We're open to a Signalfx sink if we can bring it up to the quality we require.

2020-07-21 03:58 UTC, closed without merging

2020-12-08 19:21 UTC, mengesb commented
@apestel - wondering if you deleted your source branch on this and moved on... wondering if there's a way t continue where you left off or if we're better to start anew

2020-12-08 19:22 UTC, jamtur01 commented
@mengesb Looks like the branch is still there: https://github.com/apestel/vector/tree/signalfx-sink-new

2020-12-08 19:55 UTC, apestel commented
Hi, yes still open. I'm still waiting for SFX to implement the log feature before investing more time in this PR.
This is the way :)

2020-12-09 20:37 UTC, mengesb commented
@apestel ; given that splunk owns signalfx ... and is a very well established product, I do not think, or expect, signalfx to implement a log path. That's already covered by the splunk log sink here as well - and it works **very** well.

We've sourced your diff from the PR and applied it to master citing you as co-author-by, because rebasing ~1530 commits from your PR to HEAD proved too messy. I've also pulled in the comments that weren't addressed when your PR was closed.

If you'd like to resume your work, I'd love for that to happen, and we'll respectfully back off and give you the right-of-way - you deserve it 👏 

If you still want to wait, I respect that, however we'll continue work on #5464 because we really really want to abandon the signalfx agent like we've abandoned the splunk universal forwarder --- and just use vector ❤️

2020-12-09 20:53 UTC, apestel commented
You're giving me far too much credits :).
I would have need some free time (maybe during those next holidays) to reboot the PR. Anyway it will be more a usecase for me to learn Rust and better understand Vector than something that could be prod ready (if done only by myself).

Thanks for the co-Author thing even if I'm not sure I deserve anything.
Someone in my team will be keen to test it when your new PR will be merged.

Good luck.

2020-12-09 21:04 UTC, mengesb commented
If you want permission to contribute, we're all for it --- just comment on our PR and we'll add you to contributors for the repo!

2020-12-11 10:52 UTC, apestel commented
@mengesb https://www.splunk.com/en_us/form/splunk-log-observer.html it's what I'm waiting for