fix(splunk_hec sink): Remove extra slash on Uri join
vectordotdev/vector pull request #2711
Opened 2020-05-29 20:31 UTC by fanatid

Closes #2705 (improved version of #2706)

Fixing problem in `splunk_hec` immediately fix problem in `humio_logs`.

2020-05-30 00:31 UTC, bruceg requested changes

2020-05-30 00:31 UTC, bruceg commented on src/sinks/splunk_hec.rs
> +    }
This is simply `let host = host.trim_end('/');` (which avoids the `mut`) and could possibly be merged into the format line below.

2020-06-02 04:02 UTC, bruceg approved these changes
Looks good to me.

2020-06-02 14:42 UTC, lukesteensen approved these changes

2020-06-02 15:22 UTC, merged