enhancement(file source): Enable skipping first N lines
vectordotdev/vector pull request #2907
Opened 2020-06-25 17:36 UTC by ktff

Closes #2175

### Open questions
- [ ] This PR propagates `file_id` which is used to identify a file. It's need for this enhancement to function properly. But a similar enhancement `multiline` uses file path as an identifier which should break under certain file rotation strategies.

2020-06-25 17:38 UTC, binarylogic approved these changes
Looks great to me! @lukesteensen the code review pleasure is all yours 😄.

2020-06-30 19:30 UTC, lukesteensen requested changes
This will skip the first N lines per file that are returned by the file server on each run of Vector, no matter where those lines are located in the file.

To actually skip the first N lines in each physical file I think we'll need something much more invasive and stateful, which is why I was hesitant to prioritize this feature in the first place. Feel free to take a stab at it, but I don't want to invest more time and effort into this feature than it's worth.

2020-06-30 19:41 UTC, binarylogic commented
@ktff if you find that the remaining work outweighs the benefits, let's note that on the issue and close it.

2020-07-03 10:31 UTC, ktff commented
@lukesteensen then we could only enable this feature if `start_at_beginning` is enabled, this should be enough for the use case in the issue, unless there is some other problem you see?

2020-07-03 14:40 UTC, binarylogic commented on .meta/sources/file.toml.erb
> +"""
```suggestion
"""
relevant_when = {start_at_beginning = true}
```

We should add the above if this is only relevant when `start_at_beginning` is true.

2020-07-07 19:15 UTC, ktff commented
@lukesteensen  Lines will now be skipped only if `start_at_beginning` is enabled.

2020-07-07 22:18 UTC, lukesteensen commented
I'm still a little nervous about this given that `start_at_beginning` sadly does not guarantee we'll actually start at the beginning of a file (table from #1020): 

Old | Startup | Checkpoint | start_at_beginning | Result
-- | -- | -- | -- | --
Y | - | - | - | End
N | Y | Y | Y | Beginning
N | Y | Y | N | Checkpoint
N | Y | N | Y | Beginning
N | Y | N | N | Beginning
N | N | Y | Y | Checkpoint
N | N | Y | N | Checkpoint
N | N | N | Y | Beginning
N | N | N | N | Beginning

2020-07-09 16:04 UTC, ktff commented
> I'm still a little nervous about this

For a good reason, true, this won't work. There are some checks that we could do, but these seam too complex for such a feature so I'll be closing this. At best, once #1020 is done we can come back to this.

2020-07-09 16:04 UTC, closed without merging