feat(remap): support resolving program to "any" value
vectordotdev/vector pull request #5060
Opened 2020-11-16 10:39 UTC by JeanMertz

As suggested by @FungusHumungus in https://github.com/timberio/vector/pull/4902#issuecomment-727569570.

This PR introduces the option to accept a program that resolves to "any", but only if it's final expression isn't defined to resolve to anything other than any.

That is to say, if I configure my program such that it has to resolve to a boolean, and is not allowed to resolve to any then this happens:

```rust
true // ok
.foo // error: resolves to any, not boolean
42   // error: resolves to integer, not boolean
```

If instead I were to keep the boolean constraint, but also allow resolving to any, then this changes:

```rust
true // ok
.foo // ok
42   // error: resolves to integer, not boolean
```

This will become useful when we want to use remap in string templates, e.g:

```rust
"foo {{ .bar }}" // ok, the caller of the program should make sure to coerce `.bar` to a string, or error
"foo {{ true }}" // false, a boolean isn't a string, so we can warn about this at compile-time
```

The advantage to this is such that we keep the templating logic simple, as we don't require the user to always use `to_string` when referencing a path: `"foo {{ to_string(.bar) }}"`.

---

Once we have the option to pass field types through Vector pipelines, we can refine this further, as we'd potentially know that `.foo` resolves to a boolean.

2020-11-16 17:13 UTC, bruceg reviewed
Looks ok, but I'm seeing a lot of check failures.

2020-11-16 21:41 UTC, FungusHumungus requested changes

2020-11-16 21:41 UTC, FungusHumungus commented on lib/remap-lang/src/program.rs
> +                if !program_def.kind.is_all() || !constraint.allow_any {
I don't think this is quite sufficient. Thinking about a template field, we specify we want `String` but can also accept `Any`. If we have the template field `{{.foo + .bar}}`, this is going to resolve to `String | Int | Float`. This code won't accept that.

It's almost like we want to be able to specify the `allows_any` flag to perform the contains the other way. As long as there is the potential for the script to return the type we want, we should accept it. Any other errors have to be caught at runtime as it is then that the final type is narrowed down to what we want.

The following code seems to work for what I am thinking, although I haven't fully thought through all the consequences of it yet.. There may be some repercussions around the fallible flag that this isn't taking into account.


```
        if constraint.allow_any {
                if !program_def.contains(&constraint.type_def) {
                    return Err(RemapError::from(E::from(Error::ResolvesTo(
                        ResolvesToError(constraint.type_def, program_def),
                    ))));
                }
            } else {
                if !constraint.type_def.contains(&program_def) {
                    return Err(RemapError::from(E::from(Error::ResolvesTo(
                        ResolvesToError(constraint.type_def, program_def),
                    ))));
                }
            }
```

2020-11-26 18:43 UTC, JeanMertz commented
> I don't think this is quite sufficient. Thinking about a template field, we specify we want `String` but can also accept Any. If we have the template field `{{.foo + .bar}}`, this is going to resolve to `String | Int | Float`. This code won't accept that.

That's correct. And I agree, we should iterate on this when we start integrating Remap into templating. I do think we can extend the current implementation, so I'll merge this PR to unblock a few others, but this will need another iteration when we get back to this.

2020-11-26 18:43 UTC, merged