fix(config): fixing Compression parsing with tests
vectordotdev/vector pull request #5429
Opened 2020-12-07 11:29 UTC by fanatid

Moved from https://github.com/timberio/vector/pull/5281#discussion_r536383664

2020-12-07 15:52 UTC, juchiast commented
Not introduced in this PR, but error message on `visit_str` is confusing:
```
invalid value: string "asdf", expected string or map at line 1 column 6
```

You can use
```rust
                    _ => Err(de::Error::invalid_value(
                        de::Unexpected::Str(s),
                        &r#""none" or "gzip""#,
                    )),
```

with will print
```
invalid value: string "asdf", expected none or gzip
````

Using `unknown_variant` is also fine, it will print 
```
unknown variant `asdf`, expected `none` or `gzip`
```

2020-12-07 15:53 UTC, juchiast requested changes

2020-12-07 15:53 UTC, juchiast commented on src/sinks/util/buffer/compression.rs
> +                                            de::Unexpected::Other("0, 1, 2, 3, 4, 5, 6, 7, 8 or 9"),
First parameter of `invalid_value` is the invalid value in the input, so we need to pass `level` here. I'm not sure what to do with the `None` case, maybe we convert it to a string if it is too cumbersome to conver `serde_json::Number` into `Unexpected`. 
 
Second parameter is what data was expected, using `self` as the second parameter will print "expected string or map". You can use a reference to a string here, so `&"0, 1, 2, 3, 4, 5, 6, 7, 8 or 9"` would be perfect.

2020-12-07 15:53 UTC, juchiast commented on src/sinks/util/buffer/compression.rs
> +                                        return Err(de::Error::invalid_value(
Same problem here.

2020-12-07 15:53 UTC, juchiast commented on src/sinks/util/buffer/compression.rs
> +                                        de::Unexpected::Other("Number or String"),
Same problem here. I'm not sure how to get an appropriate `Unexpected` variant here.

2020-12-07 16:56 UTC, fanatid commented
@juchiast thanks! I changed errors and added tests for them.

2020-12-08 03:08 UTC, juchiast approved these changes
Look good! Some `format!("{}", ...)` could be replaced with `to_string` to avoid macro invocation.

2020-12-08 08:18 UTC, merged

2020-12-08 08:18 UTC, fanatid commented
@juchiast thank you for review!