enhancement(gcp_stackdriver_logs sink): Allow templating in "resource.*" fields
vectordotdev/vector pull request #6357
Opened 2021-02-05 06:11 UTC by juchiast

close #5931

2021-02-05 06:16 UTC, juchiast commented on src/sinks/gcp/stackdriver_logs.rs
> +            }
I've tested with GCP to make sure healthcheck still works in this case.

2021-02-05 06:16 UTC, juchiast commented on src/vec_map.rs
> +/// Ideal to store labels map in various sinks.
I want to try this simple data structure, also useful in loki sink (https://github.com/timberio/vector/pull/5973#discussion_r563002293).

2021-02-05 14:06 UTC, jszwedko reviewed
Thanks @juchiast ! So this should work, but it looks like setting the `resource` at the top-level of the request is actually just a default for any log entries that don't have a `resource` key embedded:

> resource: Optional. A default monitored resource object that is assigned to all log entries in entries that do not specify a value for resource. Example:

https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write

I think we could actually avoid partitioning the batches by simply setting the `resource` key on the log entries themselves:

> resource: Required. The monitored resource that produced this log entry.

https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

This could be done alongside where we insert `severity` and the `jsonPayload` in `encode_event`.

`logName` is actually similar in that the top-level is just a default, so we could easily allow those to be templatable as well by moving them down into `encode_event`.

2021-02-05 20:07 UTC, bruceg requested changes
The basic approach looks sound. It needs docs and I have some questions about the new types introduced.

2021-02-05 20:07 UTC, bruceg commented on src/vec_map.rs
> +pub struct VecMap<V> {
I'm not sure I like the naming of these two structures, but the idea is reasonable. They are named `Map` but don't support any of the normal map accessors. This seems like more of a `SortedVec`.

2021-02-05 20:07 UTC, bruceg commented on src/vec_map.rs
> +    pub entries: Vec<(String, V)>,
If this has an invariant of staying sorted, it should probably not be `pub` to avoid other code from breaking that invariant.

2021-02-05 20:07 UTC, bruceg commented on src/vec_map.rs
> +}
Is this something more than a newtype wrapper around key,value pairs?

2021-02-10 03:17 UTC, juchiast reviewed
I'm in favor of inserting `resource` to each log entry to avoid partitioning, thanks @jszwedko  for pointing that out!

2021-05-14 16:48 UTC, jszwedko commented
Closing as stale. We can implement the approach suggested in https://github.com/timberio/vector/pull/6357#pullrequestreview-584351431 when we get around to picking #5931 back up.

2021-05-14 16:48 UTC, closed without merging