enhancement(vrl): add unused variable compiler error
vectordotdev/vector pull request #8912
Opened 2021-08-26 21:39 UTC by JeanMertz

ref #5780

Leaving an assigned variable unused is now a compile-time error. Previously, the program compiled as expected, but the assigned variable was never used in the result of the program.

```coffee
unused_variable = true
```

```
error[E642]: unused variable assignment
  ┌─ :2:1
  │
2 │ unused_variable = true
  │ ^^^^^^^^^^^^^^^
  │ │
  │ this variable is unused
  │ remove the assignment or use its value
  │
  = see language documentation at https://vrl.dev
```

No-op assignments (`_ = true`) are ignored, and we also allow unused variables when they start with a `_` (e.g. `_foo = true`).

Similar to #8910, you could consider this a breaking change, although I don't think it matters here either, cc @jszwedko.

2021-08-30 11:49 UTC, StephenWakely requested changes
This is great!

One problem, it messes up the `cli`.

```
$ nork = 3

error[E642]: unused variable assignment
  ┌─ :1:1
  │
1 │ nork = 3
  │ ^^^^
  │ │
  │ this variable is unused
  │ remove the assignment or use its value
  │
  = see language documentation at https://vrl.dev
```

I think somehow we need to make this an optional check. Maybe we do need to incorporate the concept of strictness, at least to allow the cli to be less strict?

2021-08-30 12:05 UTC, JeanMertz commented
> One problem, it messes up the `cli`.

Yeah, I realized the same. You can, of course, work around this by prepending the variables with `_`, but that's a sub-par experience.

I'll think about this throughout the week as I work on the RFC for iteration support, in the hopes of coming up with a satisfying solution.

2021-11-10 10:25 UTC, JeanMertz commented
Note to self: the diagnostic message should be updated, to help people with a common mistake of trying to assign to `.foo`, but assigning to `foo` instead:

```
error[E642]: unused variable assignment
  ┌─ :2:1
  │
2 │ unused_variable = true
  │ ^^^^^^^^^^^^^^^
  │ │
  │ this variable is unused
  │ remove the assignment or use its value
  │
  = try: did you mean to assign to the field `.unused_variable` instead?
  = see language documentation at https://vrl.dev
```

2022-10-06 19:27 UTC, jszwedko commented
@JeanMertz is this still relevant or should we close it?

2023-03-28 15:49 UTC, fuchsnj commented
Closing since this needs to be migrated to the new VRL repo.

2023-03-28 15:49 UTC, closed without merging