feat(new sink): Add 'websocket' sink
vectordotdev/vector pull request #9632
Opened 2021-10-15 06:37 UTC by zshell31

Closes https://github.com/vectordotdev/vector/issues/9631

Websocket sink uses the [tokio-tungstenite](https://lib.rs/crates/tokio-tungstenite) crate to connect & send events to a WebSocket server.
Supported options:
- `uri` - the WebSocket uri to connect;
- `ping_interval` (opt) - the interval during which a WebSocket ping should be sent to the server;
- `ping_timeout` (opt) - the interval during which the WebSocket server should reply on a sent ping. If the server does not reply, the sink tries to reconnect to the server.

[This PR is nominated at RU RustCon Contest](https://rustcon.ru/contest2021)

2022-01-05 20:28 UTC, fuchsnj requested changes
Overall this seems reasonable. Left a few comments.

2022-01-05 20:28 UTC, fuchsnj commented on src/sinks/websocket.rs
> +use crate::{
It would be nice if this file was broken up into multiple files. (`WebSocketSink` in 1 file, `WebSocketSinkConfig` in another, etc)

2022-01-05 20:28 UTC, fuchsnj commented on Cargo.toml
> +sinks-websocket = ["tokio-tungstenite"]
`sinks-websocket` also needs to be added to the `sinks-logs` list above, which will add it as a default feature

2022-02-14 13:45 UTC, fuchsnj approved these changes

2022-04-29 13:48 UTC, fuchsnj commented
@zshell31 Please sign our CLA so we can merge this: https://cla.datadoghq.com/vectordotdev/vector?pullRequest=9632

Thanks for your contribution!

2022-05-02 13:52 UTC, fuchsnj commented
Hey @zshell. It still looks like the CLA wasn't accepted (as reported here https://github.com/vectordotdev/vector/pull/9632#issuecomment-959755676).
If you already accepted it, can you make sure your Github account has the email address linked that you used in your commits?

2022-05-03 14:34 UTC, zshell31 commented
> Hey @zshell. It still looks like the CLA wasn't accepted (as reported here [#9632 (comment)](https://github.com/vectordotdev/vector/pull/9632#issuecomment-959755676)). If you already accepted it, can you make sure your Github account has the email address linked that you used in your commits?

Sorry, I pushed commits signed with my work email but I didn't specified the email in my profile.

2022-05-03 15:35 UTC, merged

2022-05-03 15:35 UTC, fuchsnj commented
@zshell31 Thanks again for your contribution!

2022-05-05 12:38 UTC, Dreamacro commented
Hope that there will be a websocket source as well 😆